In [1]:
import numpy as np
import pandas as pd

In [153]:
X=np.array([[1,1],[1,0],[0,1],[1,1]])
y=np.array([1,1,1,0])

In [79]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [101]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [154]:
np.random.seed(0)
Wh1=np.random.randn(2,2)
bh1=np.random.randn(1,2)
Wo=np.random.randn(2,1)
bo=np.random.randn(1,1)

In [155]:
def ForwardProp(X,Wh1,bh1,Wo,bo):
    z1=np.matmul(X,Wh1)+bh1
    a1=sigmoid(z1)
    z2=np.matmul(a1,Wo)+bo
    a2=sigmoid(z2)
    return z1,z2,a1,a2
    

In [156]:
def backProp(X,y,Wh1,bh1,Wo,bo,lr):
    z1,z2,a1,a2=ForwardProp(X,Wh1,bh1,Wo,bo)
    
    first_o=a2-y.reshape(-1,1)
    second_o=derivative_sigmoid(z2)
    first_two_o=first_o*second_o
    changes_o=np.dot(z1.T,first_two_o)
    changes_o_bias=np.sum(first_two_o,axis=0,keepdims=True)
    
    first_h=np.dot(first_two_o,Wo.T)
    second_h=derivative_sigmoid(z1)
    first_two_h=first_h*second_h
    changes_h=np.dot(X.T,first_two_h)
    changes_h_bias=np.sum(first_two_h,axis=0,keepdims=True)
    
    Wo=Wo-lr*changes_o
    bo=bo-lr*changes_o_bias
    
    Wh1=Wh1-lr*changes_h
    bh1=bh1-lr*changes_h_bias
    
    return Wh1,bh1,Wo,bo
    
    

In [157]:
def NeuralNet(X,y,Wh1,bh1,Wo,bo,lr,epochs):
    for i in range(epochs):
        Wh1,bh1,Wo,bo=backProp(X,y,Wh1,bh1,Wo,bo,lr)
    z1,z2,a1,a2=ForwardProp(X,Wh1,bh1,Wo,bo)
    print(Wh1)
    #print(z2)
    return Wh1,bh1,Wh2,bh2,z2
    

In [158]:
NeuralNet(X,y,Wh1,bh1,Wo,bo,0.01,100)

[[1.76489868 0.39935909]
 [0.98168485 2.24054478]]


(array([[1.76489868, 0.39935909],
        [0.98168485, 2.24054478]]),
 array([[ 1.8721072 , -0.98040456]]),
 array([[ 0.09500884],
        [-0.01513572]]),
 array([[-0.01032189]]),
 array([[0.78192775],
        [0.87522253],
        [0.74986269],
        [0.78192775]]))