In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
from sklearn import datasets
iris=datasets.load_iris()

In [10]:
X=iris.data
y=iris.target.reshape(-1,1)
print(X.shape,y.shape)

(150, 4) (150, 1)


In [194]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [460]:
def cost(y_pred,y):
    y_pred=np.array(y_pred)
    y=np.array(y)
    COST=-y*np.log(y_pred)-(1-y)*np.log(1-y_pred)
    return np.sum(COST)

In [222]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [236]:
def GradientStep(X,y,parameters):
    z=np.matmul(X,parameters)
    #print(z)
    y_pred=sigmoid(z)
    diff=y_pred-y
    changes=np.matmul(X.T,diff)
    return changes

In [237]:
def GradientDescent(X,y,epochs,learning_rate):
    np.random.seed(0)
    parameters=(np.random.randn(X.shape[1])/10).reshape(-1,1)
    for i in range(epochs):
        changes=GradientStep(X,y,parameters)
        parameters=parameters-learning_rate*changes
    return parameters

In [238]:
def LogisticRegressionFit(X,y,epochs=100,learning_rate=0.001):
    Ones=np.ones(X.shape[0]).reshape(-1,1)
    X=np.concatenate((Ones,X),axis=1)
    Y=pd.get_dummies(y[:,0])
    Y=Y.values
    parameters=[]
    for i in range(Y.shape[1]):
        temp_parameters=GradientDescent(X,Y[:,i],epochs,learning_rate)
        parameters.append(temp_parameters[:,0])
    parameters=np.array(parameters).T
    return parameters

In [252]:
def LogisticPredict(X_train,y_train,X,lr=0.001):
    parameters=LogisticRegressionFit(X_train,y_train,learning_rate=lr)
    Ones=np.ones(X.shape[0]).reshape(-1,1)
    X=np.concatenate((Ones,X),axis=1)
    z=np.matmul(X,parameters)
    y_pred=sigmoid(z)
    #print(y_pred)
    #print(np.argmax(y_pred,axis=1))
    return y_pred

In [258]:
LRlist=[ 0.00001*np.power(2,i) for i in range(16)]
def Best_lr(X_train,y_train,lr_matrix=LRlist):
    MinCost=sys.maxsize
    blr=0
    for i in lr_matrix:
        temp_pred=LogisticPredict(X_train,y_train,X_train)
        temp_cost=cost(temp_pred,y)
        if(temp_cost<MinCost):
            MinCost=temp_cost
            blr=i
    #print(MinCost)
    return blr

In [254]:
LogisticPredict(X_train,y_train,X_train,lr=0.001)
y_train

[[9.60876475e-04 9.99314395e-01 9.60876475e-04]
 [1.26005824e-03 9.98983478e-01 1.26005824e-03]
 [3.26648473e-04 9.99808686e-01 3.26648473e-04]
 [5.17495906e-03 9.93284186e-01 5.17495906e-03]
 [3.27901341e-04 9.99801490e-01 3.27901341e-04]
 [3.39701408e-03 9.96073064e-01 3.39701408e-03]
 [2.33569551e-03 9.96680313e-01 2.33569551e-03]
 [3.39938594e-03 9.97247606e-01 3.39938594e-03]
 [4.12424695e-04 9.99754769e-01 4.12424695e-04]
 [3.03954444e-04 9.99852709e-01 3.03954444e-04]
 [9.37067340e-04 9.99376543e-01 9.37067340e-04]
 [3.84833981e-04 9.99765683e-01 3.84833981e-04]
 [1.57334667e-03 9.98721873e-01 1.57334667e-03]
 [1.34076825e-04 9.99918237e-01 1.34076825e-04]
 [5.44315838e-04 9.99629442e-01 5.44315838e-04]
 [1.81769530e-03 9.98520530e-01 1.81769530e-03]
 [6.39608543e-04 9.99586878e-01 6.39608543e-04]
 [5.78205654e-04 9.99611090e-01 5.78205654e-04]
 [2.36625501e-03 9.98753899e-01 2.36625501e-03]
 [6.69167260e-04 9.99581738e-01 6.69167260e-04]
 [3.19260009e-04 9.99728889e-01 3.192600

array([[1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [0],
       [0],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [0],
       [1],
       [2],
       [2],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [0],
    

In [381]:
def LR(X,y,epochs=200,learning_rate=0.001):
    Ones=np.ones(X.shape[0]).reshape(-1,1)
    X=np.concatenate((Ones,X),axis=1)
    parameters=GradientDescent(X,y,epochs,learning_rate)
    return parameters

In [382]:
x=X[:100]
Y=y[:100]

In [383]:
x_train,x_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.25,random_state=0)

In [384]:
def Predict(X_train=x,y_train=Y,X=x,epochs=200,lr=0.001):
    parameters=LR(X_train,y_train,learning_rate=lr)
    Ones=np.ones(X.shape[0]).reshape(-1,1)
    X=np.concatenate((Ones,X),axis=1)
    z=np.matmul(X,parameters)
    y_pred=sigmoid(z)
    return y_pred


In [432]:
LRlist=[ 0.00001*np.power(2,i) for i in range(16)]
def Best_lr(X_train,y_train,lr_matrix=LRlist):
    COST=[]
    MinCost=sys.maxsize
    blr=0
    for i in lr_matrix:
        temp_pred=Predict(X_train,y_train,X_train)
        temp_cost=cost(temp_pred,y_train)
        COST.append((i,temp_cost))
        if(temp_cost<MinCost):
            MinCost=temp_cost
            blr=i
    return blr,MinCost

In [435]:
def MLRpredict(X_train,y_train,X_test,epochs=200,lr_matrix=LRlist,Multi=True):
    if(Multi==True):
        y_train=pd.get_dummies(y_train[:,0]).values
        Ytrain_pred=[]
        Ytest_pred=[]
    for i in range(y_train.shape[1]):
        bestLR,MinCost=Best_lr(X_train,y_train[:,i].reshape(-1,1),lr_matrix)
        print(bestLR,MinCost)
        Ytrain_pred.append(Predict(X_train,y_train[:,i].reshape(-1,1),X_train,epochs)[:,0])
        Ytest_pred.append(Predict(X_train,y_train[:,i].reshape(-1,1),X_test,epochs)[:,0])
    Ytrain_pred=np.array(Ytrain_pred).T
    Ytest_pred=np.array(Ytest_pred).T
    print(Ytrain_pred)

    return np.argmax(Ytrain_pred,axis=1),np.argmax(Ytest_pred,axis=1),Ytrain_pred

In [437]:
ypred_train,ypred_test,Ytrain_pred=MLRpredict(X_train,y_train,X_test)

1e-05 -458.0825791622472
1e-05 -9153.64692442921
1e-05 -2589.685261345544
[[3.31819458e-02 2.94965160e-01 3.01915767e-01]
 [3.59069408e-02 3.70358064e-01 2.52102275e-01]
 [2.26680626e-03 3.50787766e-01 7.61807677e-01]
 [9.58277306e-01 1.72196338e-01 1.70041773e-03]
 [4.86112092e-03 2.93061731e-01 6.31441137e-01]
 [9.37619248e-01 1.38804907e-01 2.59012579e-03]
 [9.72942837e-01 1.34738225e-01 6.59257912e-04]
 [4.06547092e-02 4.50864368e-01 3.29079250e-01]
 [2.63869876e-03 3.70301236e-01 7.50456283e-01]
 [1.60903317e-03 2.84599259e-01 8.67080403e-01]
 [2.73569520e-03 5.01255182e-01 7.66070931e-01]
 [8.31004184e-04 4.90096241e-01 8.65909798e-01]
 [3.90559228e-02 3.86618606e-01 2.55951832e-01]
 [7.88148610e-04 3.89732278e-01 8.05572946e-01]
 [1.95282237e-02 2.77038567e-01 3.54804821e-01]
 [4.04519163e-02 3.96365221e-01 2.63806169e-01]
 [5.36879520e-03 3.78002217e-01 6.44449337e-01]
 [5.26036673e-03 3.98199294e-01 6.06434172e-01]
 [6.56072410e-03 3.76424403e-01 8.29852947e-01]
 [3.18185131e-

In [468]:
Y_train=pd.get_dummies(y_train[:,0]).values[:,0]
ytrue=Y_train
ypred=Predict(X_train,Y_train.reshape(-1,1),X_train)
#print(ypred.shape)
#print(ypred)
cost(ypred[:,0],ytrue)
ypred=np.array(ypred[:,0])
ytrue*np.log(ypred)+(1-ytrue)*np.log(1-ypred)


array([-3.37449561e-02, -3.65674546e-02, -2.26937935e-03, -4.26180794e-02,
       -4.87297460e-03, -6.44113316e-02, -2.74299475e-02, -4.15042159e-02,
       -2.64218626e-03, -1.61032906e-03, -2.73944405e-03, -8.31349659e-04,
       -3.98390641e-02, -7.88459362e-04, -1.97214188e-02, -4.12928515e-02,
       -5.38325898e-03, -5.27425118e-03, -6.58234024e-03, -3.18692416e-03,
       -2.46207835e-02, -4.01207587e-03, -3.00908089e-02, -8.20666186e-02,
       -2.95413695e-03, -2.48935979e-02, -9.78784904e-02, -2.75019336e-02,
       -1.80568460e-02, -1.58804303e-03, -2.81926488e-02, -3.87878426e-02,
       -2.37895564e-03, -4.02714735e-02, -5.81053718e-02, -1.21918512e-02,
       -1.33526509e-02, -7.19817887e-02, -4.81165251e-03, -1.81334175e-01,
       -4.44627162e-02, -7.53973695e-03, -1.25944217e-03, -3.28950359e-02,
       -5.93946486e-02, -1.14582175e-03, -1.75359213e-03, -1.08607476e-03,
       -1.29951367e-03, -3.17306678e-02, -5.67112429e-02, -6.26480121e-03,
       -2.20433631e-03, -

In [305]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix
cm(Y_pred[:,0],Y_test[:,0])

array([[13,  0],
       [ 0, 12]])

In [398]:
Predict(X,y,X)[:,0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [315]:
Y=pd.get_dummies(y[:,0]).values
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [329]:
Y_pred0=predict(X_train,Y_train[:,0].reshape(-1,1),X_test)
result0=np.concatenate((Y_pred0,Y_test[:,0].reshape(-1,1)),axis=1)
result0

(112, 4) (112, 1)


array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0]])

In [335]:
Y_pred1=predict(X_train,Y_train[:,1].reshape(-1,1),X_test)
result1=np.concatenate((Y_pred1,Y_test[:,1].reshape(-1,1)),axis=1)
result1

(112, 4) (112, 1)


array([[0.37643563, 0.        ],
       [0.39145523, 1.        ],
       [0.10831   , 0.        ],
       [0.42020111, 0.        ],
       [0.16537645, 0.        ],
       [0.36414068, 0.        ],
       [0.14996121, 0.        ],
       [0.30894159, 1.        ],
       [0.34830327, 1.        ],
       [0.31460795, 1.        ],
       [0.4455676 , 0.        ],
       [0.29260838, 1.        ],
       [0.36166392, 1.        ],
       [0.34068987, 1.        ],
       [0.34678938, 1.        ],
       [0.19026415, 0.        ],
       [0.33450861, 1.        ],
       [0.37977737, 1.        ],
       [0.19310737, 0.        ],
       [0.12048977, 0.        ],
       [0.37430664, 0.        ],
       [0.33249604, 1.        ],
       [0.18519935, 0.        ],
       [0.2091586 , 0.        ],
       [0.35624395, 0.        ],
       [0.1389371 , 0.        ],
       [0.15046654, 0.        ],
       [0.32018509, 1.        ],
       [0.35644033, 1.        ],
       [0.16746043, 0.        ],
       [0.

In [364]:
y_pred0=predict(X,Y[:,0].reshape(-1,1),X,lr=0.0012)
result=np.concatenate((y_pred0,Y[:,0].reshape(-1,1)),axis=1)
result

(150, 4) (150, 1)


array([[9.61770608e-01, 1.00000000e+00],
       [9.28868354e-01, 1.00000000e+00],
       [9.49891305e-01, 1.00000000e+00],
       [9.19569254e-01, 1.00000000e+00],
       [9.65163223e-01, 1.00000000e+00],
       [9.56909029e-01, 1.00000000e+00],
       [9.48226561e-01, 1.00000000e+00],
       [9.47813847e-01, 1.00000000e+00],
       [9.10868793e-01, 1.00000000e+00],
       [9.29770227e-01, 1.00000000e+00],
       [9.66501203e-01, 1.00000000e+00],
       [9.35230778e-01, 1.00000000e+00],
       [9.31945297e-01, 1.00000000e+00],
       [9.54020639e-01, 1.00000000e+00],
       [9.87438112e-01, 1.00000000e+00],
       [9.84335059e-01, 1.00000000e+00],
       [9.78535358e-01, 1.00000000e+00],
       [9.59021327e-01, 1.00000000e+00],
       [9.57945186e-01, 1.00000000e+00],
       [9.65668296e-01, 1.00000000e+00],
       [9.33319941e-01, 1.00000000e+00],
       [9.58640220e-01, 1.00000000e+00],
       [9.80955522e-01, 1.00000000e+00],
       [9.02589321e-01, 1.00000000e+00],
       [8.938345

In [365]:
y_pred1=predict(X,Y[:,1].reshape(-1,1),X,lr=0.0012)
result=np.concatenate((y_pred1,Y[:,1].reshape(-1,1)),axis=1)
result

(150, 4) (150, 1)


array([[0.25217525, 0.        ],
       [0.32259151, 0.        ],
       [0.2770332 , 0.        ],
       [0.31046368, 0.        ],
       [0.23666548, 0.        ],
       [0.22381944, 0.        ],
       [0.25182946, 0.        ],
       [0.27386504, 0.        ],
       [0.32694098, 0.        ],
       [0.3220867 , 0.        ],
       [0.24007864, 0.        ],
       [0.27945614, 0.        ],
       [0.32499422, 0.        ],
       [0.28244259, 0.        ],
       [0.1858227 , 0.        ],
       [0.1575374 , 0.        ],
       [0.19141162, 0.        ],
       [0.24811088, 0.        ],
       [0.24666435, 0.        ],
       [0.21766743, 0.        ],
       [0.30287148, 0.        ],
       [0.22658931, 0.        ],
       [0.1960532 , 0.        ],
       [0.2978738 , 0.        ],
       [0.31020262, 0.        ],
       [0.3469363 , 0.        ],
       [0.27505825, 0.        ],
       [0.26366229, 0.        ],
       [0.26834414, 0.        ],
       [0.30762692, 0.        ],
       [0.

In [366]:
y_pred2=predict(X,Y[:,2].reshape(-1,1),X,lr=0.0012)
result=np.concatenate((y_pred2,Y[:,2].reshape(-1,1)),axis=1)
result

(150, 4) (150, 1)


array([[1.48029685e-03, 0.00000000e+00],
       [2.90223177e-03, 0.00000000e+00],
       [2.55452894e-03, 0.00000000e+00],
       [4.23862984e-03, 0.00000000e+00],
       [1.50024883e-03, 0.00000000e+00],
       [1.51940024e-03, 0.00000000e+00],
       [3.12009149e-03, 0.00000000e+00],
       [2.10623118e-03, 0.00000000e+00],
       [5.39415364e-03, 0.00000000e+00],
       [2.72633775e-03, 0.00000000e+00],
       [1.04548775e-03, 0.00000000e+00],
       [3.03636344e-03, 0.00000000e+00],
       [2.84785764e-03, 0.00000000e+00],
       [3.03991802e-03, 0.00000000e+00],
       [3.26081452e-04, 0.00000000e+00],
       [5.11273672e-04, 0.00000000e+00],
       [8.18654894e-04, 0.00000000e+00],
       [1.67694041e-03, 0.00000000e+00],
       [1.07091746e-03, 0.00000000e+00],
       [1.48333679e-03, 0.00000000e+00],
       [1.87921047e-03, 0.00000000e+00],
       [1.84302549e-03, 0.00000000e+00],
       [1.23444087e-03, 0.00000000e+00],
       [4.11159475e-03, 0.00000000e+00],
       [4.822055

In [367]:
y_pred=np.concatenate((y_pred0,y_pred1,y_pred2),axis=1)
YCompare=np.concatenate((y_pred0,y_pred1,y_pred2,y),axis=1)

In [371]:
Y=np.argmax(y_pred,axis=1).reshape(-1,1)
np.concatenate((Y,y),axis=1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1,