In [115]:
import os
import pandas as pd
import numpy as np
import sys

In [116]:
os.chdir("/home/abhishek/Downloads")
data = pd.read_csv("training_boston.csv")

In [117]:
def GradientStep(X,y,parameters):
    m=X.shape[0]
    y_pred=np.matmul(X,parameters)
    diff=y_pred-y.reshape(-1,1)
    changes=(2/m)*np.matmul(X.T,diff)
    return changes
    

In [118]:
def GradientDescent(X,y,parameters,epochs,learning_rate):
    for i in range(epochs):
        changes=GradientStep(X,y,parameters)
        parameters=parameters-learning_rate*changes
    return parameters

In [129]:
def LinearRegression(X,y,epochs=100,learning_rate=0.0001):
    Ones=np.ones(X.shape[0]).reshape(-1,1)
    X=np.concatenate((Ones,X),axis=1)
    rows=X.shape[0]
    cols=X.shape[1]
    parameters=np.zeros(cols).reshape(-1,1)
    parameters=GradientDescent(X,y,parameters,epochs,learning_rate)
    return parameters

In [130]:
def cost(y_pred,y):
    return np.sum(np.square(y_pred-y))/(len(y))

In [131]:
##Choose Best learning Rate
lr=[ 0.00001*pow(2,i) for i in range(16)]
def best_lr(X,y,lr_list=lr):
    MinCost=sys.maxsize
    BestLR=0
    CostList=[]
    for i in lr_list:
        p=LinearRegression(X,y,learning_rate=i)
        Ones=np.ones(X.shape[0]).reshape(-1,1)
        y_pred=np.matmul(np.concatenate((Ones,X),axis=1),p).T[0]
        temp=cost(y_pred,y.T[0])
        CostList.append((i,temp))
        if(temp<MinCost):
            MinCost=temp
            BestLR=i
    return BestLR


In [132]:
data.head()

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1 -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2  0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3  0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4 -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   

        DIS       RAD       TAX   PTRATIO         B     LSTAT     Y  
0 -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1  0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2 -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3 -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4  0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5

In [133]:
X=data.iloc[:,:13].values
y=data.iloc[:,13].values

In [134]:
def PredictY(X_train,y_train,X_test):
    Lr=best_lr(X_train,y_train.reshape(-1,1))
    parameters=LinearRegression(X_train,y_train.reshape(-1,1),learning_rate=Lr)
    print("Best LR=",Lr)
    Ones=np.ones(X_test.shape[0]).reshape(-1,1)
    X_test=np.concatenate((Ones,X_test),axis=1)
    y_pred=np.matmul(X_test,parameters)
    print("Parameters=",parameters[:,0].tolist())
    return y_pred

In [135]:
X_train=X
y_train=y
test_data=pd.read_csv('test_boston.csv')
X_test=test_data.values
X_test.shape

(126, 13)

In [139]:
from sklearn.preprocessing import StandardScaler
scX=StandardScaler()
X_train=scX.fit_transform(X_train)
X_test=scX.transform(X_test)
scy=StandardScaler()
y_train=scy.fit_transform(y_train.reshape(-1,1))

In [140]:
y_pred=PredictY(X_train,y_train,X_test)
y_pred=scy.inverse_transform(y_pred)
#y_test=scy.inverse_transform(y_test)
print(y_pred)
#cost(y_pred,y_test)

Best LR= 0.08192
Parameters= [1.5147046326096902e-16, -0.1004741822294872, 0.06427639812468787, -0.02860908427264972, 0.09035968984049796, -0.2137073923814177, 0.2584417035370472, 0.008396363381805102, -0.31197932904749504, 0.20352289490472156, -0.10790473660179553, -0.23494368525829365, 0.0628199541625212, -0.45926500537749754]
[[28.83354396]
 [22.41439668]
 [24.3060834 ]
 [20.94443808]
 [ 2.79443274]
 [29.90351576]
 [24.68074045]
 [18.77554093]
 [23.50965558]
 [24.19267122]
 [17.84006288]
 [18.04813774]
 [21.8288407 ]
 [42.50352397]
 [24.05420224]
 [24.46953025]
 [27.73157426]
 [20.40863802]
 [31.37967373]
 [24.13281006]
 [24.87918285]
 [33.88183024]
 [36.2182659 ]
 [32.19011893]
 [16.4224114 ]
 [23.39972613]
 [33.18095228]
 [24.84316442]
 [33.63542559]
 [17.04240411]
 [26.22982273]
 [23.38289813]
 [25.44831846]
 [14.99463272]
 [29.59316273]
 [26.21319989]
 [20.65718346]
 [24.21516428]
 [ 9.473497  ]
 [ 8.09363059]
 [28.852436  ]
 [29.65636072]
 [19.94500079]
 [20.31673547]
 [ 2.9854

In [141]:
np.savetxt('Boston_pred.csv', y_pred[:,0], delimiter=',')

In [143]:
from sklearn.linear_model import LinearRegression
lr1=LinearRegression()
lr1.fit(X_train,y_train)
y_pred1=scy.inverse_transform(lr1.predict(X_test))

In [150]:
lr1.coef_

array([[-0.10664855,  0.07898455,  0.00126694,  0.08723788, -0.23151139,
         0.25102769,  0.01294126, -0.32316528,  0.27414947, -0.18498221,
        -0.2398584 ,  0.06364974, -0.46106581]])

In [145]:
y_pred1

array([[29.03367318],
       [22.37164455],
       [24.47778655],
       [20.60166977],
       [ 2.72533175],
       [30.40000409],
       [24.86120042],
       [18.65724977],
       [23.53985838],
       [24.11396872],
       [17.71143854],
       [17.44000298],
       [21.65356278],
       [42.31137694],
       [23.84974493],
       [24.47573232],
       [27.53872655],
       [20.23606694],
       [31.15155453],
       [23.78237904],
       [25.00979443],
       [33.95768541],
       [36.43515649],
       [32.04098329],
       [16.71322632],
       [23.47176611],
       [32.93828009],
       [25.1807008 ],
       [33.71008685],
       [16.88580202],
       [26.02760837],
       [23.27040025],
       [25.47758968],
       [15.00946631],
       [29.5857494 ],
       [26.24821245],
       [20.37245654],
       [24.43681498],
       [ 9.44706894],
       [ 8.38096654],
       [29.01392345],
       [29.59085403],
       [19.7575697 ],
       [20.3719679 ],
       [ 3.14442625],
       [39