In [1]:
import numpy as np
import tensorflow as tf

/home/abhishek/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess=tf.Session()

In [3]:
### RNN_CELL_FORWARD

def rnn_cell_forward(xt,a_prev,parameters):
    
    Wax=parameters["Wax"]
    Waa=parameters["Waa"]
    Wya=parameters["Wya"]
    ba=parameters["ba"]
    by=parameters["by"]
    
    a_next=np.tanh(np.dot(Waa,a_prev)+np.dot(Wax,xt)+ba)
    yt_pred=sess.run(tf.nn.softmax(np.dot(Wya,a_next)+by))
    
    cache=(a_next,a_prev,xt,parameters)
    
    return a_next,yt_pred,cache

In [4]:
np.random.seed(1)
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
Waa = np.random.randn(5,5)
Wax = np.random.randn(5,3)
Wya = np.random.randn(2,5)
ba = np.random.randn(5,1)
by = np.random.randn(2,1)
parameters = {"Waa": Waa, "Wax": Wax, "Wya": Wya, "ba": ba, "by": by}

a_next, yt_pred, cache = rnn_cell_forward(xt, a_prev, parameters)
print("a_next[4] = ", a_next[4])
print("a_next.shape = ", a_next.shape)
print("yt_pred[1] =", yt_pred[1])
print("yt_pred.shape = ", yt_pred.shape)

a_next[4] =  [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape =  (5, 10)
yt_pred[1] = [0.19872856 0.00066249 0.00214437 0.00257758 0.0441077  0.00921221
 0.01102142 0.23530417 0.48830784 0.00793366]
yt_pred.shape =  (2, 10)


In [5]:
def rnn_forward(x,a0,parameters):
    
    caches=[]
    

In [6]:
Wya

array([[-0.02461696, -0.77516162,  1.27375593,  1.96710175, -1.85798186],
       [ 1.23616403,  1.62765075,  0.3380117 , -1.19926803,  0.86334532]])

In [9]:
np.dot(Wya,a_next)

array([[-1.76997444,  1.07658729, -0.50058125, -1.09297351, -3.37670313,
        -2.44450824,  0.35560085, -2.80882702, -2.73870607,  1.02484923],
       [ 1.5679518 , -4.13573059, -2.96114155, -2.77713609,  0.06264623,
        -1.50345841, -1.32414696,  1.73689096,  2.46695798, -1.65287367]])

In [10]:
by

array([[-0.62353073],
       [ 0.52057634]])

In [11]:
(np.dot(Wya,a_next)+by)

array([[-2.39350517,  0.45305656, -1.12411198, -1.71650424, -4.00023386,
        -3.06803897, -0.26792988, -3.43235775, -3.3622368 ,  0.4013185 ],
       [ 2.08852814, -3.61515426, -2.44056522, -2.25655976,  0.58322257,
        -0.98288207, -0.80357062,  2.2574673 ,  2.98753431, -1.13229733]])

In [12]:
sess.run(tf.nn.softmax((np.dot(Wya,a_next)+by)))

array([[0.02002566, 0.34501102, 0.07126518, 0.03940984, 0.004016  ,
        0.01020095, 0.16776932, 0.00708629, 0.00760102, 0.32761472],
       [0.19872856, 0.00066249, 0.00214437, 0.00257758, 0.0441077 ,
        0.00921221, 0.01102142, 0.23530417, 0.48830784, 0.00793366]])