In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

/home/abhishek/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [3]:
sess=tf.Session()

In [4]:
my_tensor=tf.zeros([1,20])

In [5]:
my_tensor

<tf.Tensor 'zeros:0' shape=(1, 20) dtype=float32>

In [6]:
sess.run(my_tensor)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [9]:
my_tensor.dtype

tf.float32

In [13]:
my_var=tf.Variable(tf.zeros([1,20]))

In [16]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [17]:
row_dim=2
col_dim=3

In [18]:
zero_var=tf.Variable(tf.zeros([row_dim,col_dim]))
one_var=tf.Variable(tf.ones([row_dim,col_dim]))

In [20]:
sess.run(zero_var.initializer)
sess.run(one_var.initializer)
print(sess.run(zero_var))
print(sess.run(one_var))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
zero_similar=tf.Variable(tf.zeros_like(zero_var))
one_similar=tf.Variable(tf.ones_like(one_var))

In [23]:
sess.run(zero_similar.initializer)
sess.run(one_similar.initializer)

print(sess.run(zero_similar))
print(sess.run(one_similar))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
fill_var=tf.Variable(tf.fill([row_dim,col_dim],-1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


In [27]:
const_var=tf.Variable(tf.constant([8,6,7,5,3,0,9]))

const_fill_var=tf.Variable(tf.constant(-1,shape=[row_dim,col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


In [35]:
linear_var=tf.Variable(tf.linspace(start=0.0,stop=1,num=3))

sequence_var=tf.Variable(tf.range(start=6,limit=15,delta=3))

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[0.  0.5 1. ]
[ 6  9 12]


In [36]:
rnorm_var=tf.random_normal([row_dim,col_dim],mean=0.0,stddev=1.0)
runif_var=tf.random_uniform([row_dim,col_dim],minval=0,maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[-0.95327294  1.0895535  -0.9564592 ]
 [ 1.6703565  -1.4552763   0.44167355]]
[[3.3873463 0.8875046 3.9815454]
 [1.7238402 1.1455417 3.2453203]]


In [38]:
ops.reset_default_graph()

sess=tf.Session()

my_var=tf.Variable(tf.zeros([1,20]))

merged=tf.summary.merge_all()

writer=tf.summary.FileWriter("/tmp/variable_logs",graph=sess.graph)

initialize_op=tf.global_variables_initializer()

sess.run(initialize_op)

In [42]:
x=tf.placeholder(tf.float32,shape=(4,4))

rand_array=np.random.rand(4,4)
y=tf.identity(x)

sess.run(y,feed_dict={x:rand_array})

array([[0.0220232 , 0.95870537, 0.7455157 , 0.50176907],
       [0.2842596 , 0.8472926 , 0.8817009 , 0.56906044],
       [0.10853851, 0.01701323, 0.44428396, 0.19562158],
       [0.02949301, 0.74090594, 0.08543736, 0.00739077]], dtype=float32)

In [44]:
identity_matrix=tf.diag([1.0,1.0,1.0])
sess.run(identity_matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [46]:
A=tf.truncated_normal([2,3])
sess.run(A)

array([[-1.1135998 , -0.56784165,  1.2998945 ],
       [-1.4330243 , -0.92316234, -0.60034895]], dtype=float32)

In [48]:
B=tf.fill([2,3],5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [50]:
C=tf.random_uniform([3,2])
print(sess.run(C))

[[0.81965923 0.6844126 ]
 [0.05180919 0.754475  ]
 [0.5907973  0.75842404]]


In [65]:
D=tf.convert_to_tensor(a)
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [60]:
a=np.array([[1.,2.,3.],[-3.,-7.,-1.],[0.,5.,-2.]])

In [63]:
tf.convert_to_tensor(a)

<tf.Tensor 'Const_2:0' shape=(3, 3) dtype=float64>

In [66]:
print(sess.run(A+B))
print(sess.run(B-B))

[[5.6030626 5.367039  5.5770106]
 [5.001233  4.2254033 4.8339357]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [67]:
print(sess.run(tf.matmul(B,identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [69]:
print(sess.run(tf.transpose(C)))

[[0.36123824 0.7791811  0.849162  ]
 [0.44331706 0.261899   0.539353  ]]


In [71]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


In [72]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [86]:
my_array=np.array([[1.,3.,5.,7.,9.],
         [-2.,-0.,2.,4.,6.],
         [-6.,-3.,-0.,3.,6.]])

x_vals=np.array([my_array,my_array+1])

In [79]:
x_data=tf.placeholder(tf.float32,shape=(3,5))
m1=tf.constant([[1.],[0.],[-1.],[2.],[4.]])
m2=tf.constant([[2.]])
a1=tf.constant([[10.]])

In [80]:
prod1=tf.matmul(x_data,m1)


In [81]:
prod2=tf.matmul(prod1,m2)

In [82]:
add1=tf.add(prod2,a1)

In [88]:
for x_val in x_vals:
    print(x_val)
    print(sess.run(add1,feed_dict={x_data:x_val}))

[[ 1.  3.  5.  7.  9.]
 [-2. -0.  2.  4.  6.]
 [-6. -3. -0.  3.  6.]]
[[102.]
 [ 66.]
 [ 58.]]
[[ 2.  4.  6.  8. 10.]
 [-1.  1.  3.  5.  7.]
 [-5. -2.  1.  4.  7.]]
[[114.]
 [ 78.]
 [ 70.]]
